import 'package:faithconnect/app/core/services/notification_services.dart';
import 'package:faithconnect/app/core/theme/app_theme.dart';
import 'package:faithconnect/app/routes/app_pages.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'firebase_options.dart'; // ← This file is REQUIRED (generated by FlutterFire CLI)

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // ✅ Initialize Firebase with platform-specific options
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint("Firebase initialized successfully");
  } catch (e) {
    debugPrint("Firebase initialization failed: $e");
    // Optionally show error UI or retry
  }

  // ✅ Initialize notifications AFTER Firebase
  await NotificationService.init();

  // ✅ Theme controller (permanent so it survives navigation)
  Get.put(ThemeController(), permanent: true);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final themeController = Get.find<ThemeController>();

    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'FaithConnect',
      theme: lightTheme,
      darkTheme: darkTheme,
      themeMode: themeController.themeMode,
      initialRoute: AppPages.INITIALPAGE, // Splash or initial route
      getPages: AppPages.routes,
      defaultTransition: Transition.leftToRight,
      transitionDuration: const Duration(milliseconds: 350),
      builder: (context, child) {
        return AnimatedSwitcher(
          duration: const Duration(milliseconds: 300),
          child: child ?? const SizedBox.shrink(),
        );
      },
    );
  }
}